name: Auto-Update Game List

on:
  # This runs the job on a schedule. This example runs at 00:00 and 12:00 UTC every day.
  # Use https://crontab.guru to customize your schedule.
  schedule:
    - cron: '0 0,12 * * *'
  
  # This allows you to run the job manually from the Actions tab.
  workflow_dispatch:

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest # Use a standard Linux virtual machine

    steps:
      # Check out the repository code so the runner can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      # Install the required Python libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the scraper script
      - name: Run the scraper
        run: python scraper.py

      # Commit the updated links_reformatted.json file back to the repository
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Updated game list"
          file_pattern: "links_reformatted.json"
